// <auto-generated />
using System;
using CarOrderingWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarOrderingWebApi.Migrations
{
    [DbContext(typeof(CarOrderingDBContext))]
    [Migration("20190821154927_changes")]
    partial class changes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarOrderingWebApi.Models.Cars", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarImgUrl");

                    b.Property<string>("CarName");

                    b.Property<decimal>("CarPrice");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new { CarId = 1, CarImgUrl = "Audi.jpg", CarName = "Audi", CarPrice = 4343439m },
                        new { CarId = 2, CarImgUrl = "benz.jpeg", CarName = "Benz", CarPrice = 3545688m },
                        new { CarId = 3, CarImgUrl = "jaguar.jpg", CarName = "Jaguar", CarPrice = 5678777m },
                        new { CarId = 4, CarImgUrl = "ferrari.jpg", CarName = "Ferrari", CarPrice = 63468327m },
                        new { CarId = 5, CarImgUrl = "lamborghini.jpg", CarName = "Lamborghini", CarPrice = 976253562m },
                        new { CarId = 6, CarImgUrl = "skoda.jpg", CarName = "Skoda", CarPrice = 672637373m }
                    );
                });

            modelBuilder.Entity("CarOrderingWebApi.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<int?>("RegisterId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("RegisterId");

                    b.ToTable("Login");

                    b.HasData(
                        new { Id = 1, Password = "admin", RegisterId = 1, Username = "admin@neudesic.com" }
                    );
                });

            modelBuilder.Entity("CarOrderingWebApi.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarId");

                    b.Property<string>("OrderIdCode");

                    b.Property<int?>("RegistrationId");

                    b.HasKey("OrderId");

                    b.HasIndex("CarId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("CarOrderingWebApi.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Contact");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Register");

                    b.HasData(
                        new { Id = 1, FirstName = "Admin", LastName = "Admin" }
                    );
                });

            modelBuilder.Entity("CarOrderingWebApi.Models.Login", b =>
                {
                    b.HasOne("CarOrderingWebApi.Models.Register", "Register")
                        .WithMany()
                        .HasForeignKey("RegisterId");
                });

            modelBuilder.Entity("CarOrderingWebApi.Models.Order", b =>
                {
                    b.HasOne("CarOrderingWebApi.Models.Cars", "Car")
                        .WithMany("Orders")
                        .HasForeignKey("CarId");

                    b.HasOne("CarOrderingWebApi.Models.Register", "Registration")
                        .WithMany("Orders")
                        .HasForeignKey("RegistrationId");
                });
#pragma warning restore 612, 618
        }
    }
}
