// <auto-generated />
using System;
using CarOrderingWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarOrderingWebApi.Migrations
{
    [DbContext(typeof(CarOrderingDBContext))]
    [Migration("20190813235705_tables")]
    partial class tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarOrderingWebApi.Models.Cars", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarName");

                    b.Property<decimal>("CarPrice");

                    b.HasKey("CarId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarOrderingWebApi.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<int?>("RegisterId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("RegisterId");

                    b.ToTable("Login");

                    b.HasData(
                        new { Id = 1, Password = "admin", RegisterId = 1, Username = "admin@neudesic.com" }
                    );
                });

            modelBuilder.Entity("CarOrderingWebApi.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarId");

                    b.Property<int?>("RegistrationId");

                    b.HasKey("OrderId");

                    b.HasIndex("CarId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("CarOrderingWebApi.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Contact");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Register");

                    b.HasData(
                        new { Id = 1, FirstName = "Admin", LastName = "Admin" }
                    );
                });

            modelBuilder.Entity("CarOrderingWebApi.Models.Login", b =>
                {
                    b.HasOne("CarOrderingWebApi.Models.Register", "Register")
                        .WithMany()
                        .HasForeignKey("RegisterId");
                });

            modelBuilder.Entity("CarOrderingWebApi.Models.Order", b =>
                {
                    b.HasOne("CarOrderingWebApi.Models.Cars", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.HasOne("CarOrderingWebApi.Models.Register", "Registration")
                        .WithMany()
                        .HasForeignKey("RegistrationId");
                });
#pragma warning restore 612, 618
        }
    }
}
